# Generated by Django 4.2.28 on 2026-02-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_event_t_996a6f_idx',
            old_name='core_event_event_ty_1763ff_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_page_0696ec_idx',
            old_name='core_event_page_30d268_idx',
        ),
    ]
